node_lines:
  - node_line_name: retrieve_node_line
    nodes:
      - node_type: retrieval
        strategy:
        modules:
          - module_type: hybrid_cc
            target_module_params:
              - bm25_tokenizer: ko_kiwi
                top_k: 3
              - embedding_batch: 100
                embedding_model: bge-m3
                top_k: 3
            target_modules: [ bm25, vectordb ]
            weights: [ 0.7 ,0.3 ]
            top_k: 3
      - node_type: passage_reranker
        strategy:
        top_k: 3
        modules:
          - module_type: koreranker
  - node_line_name: post_retrieve_node_line
    nodes:
      - node_type: prompt_maker
        strategy:
        modules:
          - module_type: fstring
            prompt: "단락을 읽고 질문에 답하세요. \n 질문 : {query} \n 단락: {retrieved_contents} \n 답변 :\n"
      - node_type: generator
        strategy:
          metrics: 
            - metric_name: rouge
            - embedding_model: openai
              metric_name: sem_score
        modules:
          - module_type: llama_index_llm
            llm: ollama
            model: [ gamma2, llama3, qwen2, mistral, EEVE-Korean-10.8B ]
            temperature: 0.1
            max_retries: 20
            batch: 1

